import turtle

def turtleLetter(letter,tur):
    if letter=="box":
        tur.setheading(0)
        tur.forward(40)
        tur.right(90)
        tur.forward(60)
        tur.right(90)
        tur.forward(40)
        tur.right(90)
        tur.forward(60)
   
    elif letter == "A":
        tur.setheading(0)
        tur.pu()
        tur.fd(5)
        tur.right(90)
        tur.fd(5)
        tur.pd()
        tur.fd(30)
        tur.right(180)
        tur.fd(30)
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(30)
        tur.right(180)
        tur.fd(15)
        tur.left(90)
        tur.fd(20)
        tur.pu()
        #fixes
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(35)
        #tur.right(180)
    elif letter == "B":
        tur.setheading(0)
        tur.pu()
        tur.fd(5)
        tur.right(90)
        tur.fd(5)
        tur.pd()
        tur.fd(30)
        tur.left(90)
        tur.fd(20)
        tur.left(90)
        tur.fd(15)
        tur.left(90)
        tur.fd(20)
        tur.left(180)
        tur.fd(20)
        tur.left(90)
        tur.forward(15)
        tur.left(90)
        tur.fd(20)
        #fix
        tur.pu()
        tur.left(180)
        tur.fd(35)
    elif letter == "C":
        tur.pu()
        tur.fd(20)
        tur.right(180)
        tur.pd()
        tur.circle(15,180)
        #fix
        tur.pu()
        tur.left(90)
        tur.fd(30)
        tur.right(90)
        tur.fd(20)
    elif letter == "D":
        tur.pd()
        tur.right(90)
        tur.fd(30)
        tur.left(90)
        tur.circle(15,180)
        #fix
        tur.pu()
        tur.right(180)
        tur.fd(30)
    elif letter == "E":
        tur.pd()
        tur.fd(20)
        tur.right(180)
        tur.fd(20)
        tur.left(90)
        tur.fd(15)
        tur.left(90)
        tur.fd(20)
        tur.left(180)
        tur.fd(20)
        tur.left(90)
        tur.fd(15)
        tur.left(90)
        tur.fd(20)
        #fix
        tur.pu()
        tur.left(90)
        tur.fd(30)
        tur.right(90)
        tur.fd(10)
    elif letter == "F":
        tur.pd()
        tur.fd(20)
        tur.right(180)
        tur.fd(20)
        tur.left(90)
        tur.fd(15)
        tur.left(90)
        tur.fd(15)
        tur.left(180)
        tur.fd(15)
        tur.left(90)
        tur.fd(15)
        #fix
        tur.pu()
        tur.left(180)
        tur.fd(30)
        tur.right(90)
        tur.fd(30)
    
    elif letter == "G":
        tur.penup()
        tur.forward(5)
        tur.right(90)
        tur.forward(5)
        tur.left(90)
        tur.pendown()
        tur.forward(30)
        tur.left(180)
        tur.forward(30)
        tur.left(90)
        tur.forward(50)
        tur.left(90)
        tur.forward(30)
        tur.left(90)
        tur.forward(20)
        tur.left(90)
        tur.forward(10)
        tur.penup()
        tur.forward(10)
        tur.right(90)
        tur.forward(30)
        tur.right(90)
        tur.forward(30)     
    elif letter == "H":
        tur.pd()
        tur.right(90)
        tur.fd(30)
        tur.left(180)
        tur.fd(15)
        tur.right(90)
        tur.fd(20)
        tur.left(90)
        tur.fd(15)
        tur.left(180)
        tur.fd(30)
        #fix
        tur.pu()
        tur.right(180)
        tur.fd(30)
        tur.right(90)
        tur.fd(10)
    elif letter == "I":
        tur.pd()
        tur.fd(20)
        tur.left(180)
        tur.fd(10)
        tur.left(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(10)
        tur.left(180)
        tur.fd(20)
        #fix
        tur.pu()
        tur.right(90)
        tur.fd(30)
        tur.right(90)
        tur.fd(30)
    elif letter == "J":
        tur.pu()
        tur.fd(30)
        tur.right(90)
        tur.pd()
        tur.fd(30)
        tur.pu()
        tur.setheading(180)
        tur.forward(30)
        tur.setheading(270)
        tur.pd()
        tur.circle(15,180)
        tur.pu()
        tur.fd(30)
        tur.right(90)
        tur.fd(10)
        tur.pd()
        
    elif letter == "K":
        tur.pu()
        tur.fd(10)
        tur.right(90)
        tur.pd()
        tur.forward(60)
        tur.right(180)
        tur.fd(30)
        tur.right(30)
        tur.fd(30)
        tur.right(180)
        tur.fd(30)
        tur.setheading(310)
        tur.fd(30)
        tur.right(180)
        tur.fd(30)
        tur.setheading(90)
        tur.pu()
        tur.fd(30)
        tur.right(90)
        tur.fd(30)
        tur.pd()
    elif letter == "L":
        tur.pd()
        tur.right(90)
        tur.forward(30)
        tur.left(90)
        tur.forward(20)
        tur.pu()
        tur.left(90)
        tur.fd(30)
        tur.right(90)
        tur.fd(10)
    
      
    elif letter == "M":
        tur.pu()
        tur.right(90)
        tur.fd(30)
        tur.left(90)
        tur.pd()
        tur.left(45)
        tur.forward(20)
        tur.right(90)
        tur.forward(20)
        tur.left(90)
        tur.forward(20)
        tur.right(90)
        tur.forward(20)
        tur.pu()
        tur.left(45)
        tur.left(90)
        tur.fd(30)
        tur.right(90)
        tur.fd(10)  
        
    elif letter == "N":
        tur.pd()
        tur.right(90)
        tur.fd(40)
        tur.left(180)
        tur.forward(40)
        tur.right(135)
        tur.forward(40)
        tur.left(135)
        tur.forward(40)
        tur.pu()
        tur.right(90)
        tur.fd(10)
        
    
    elif letter == "O":
        tur.pu()
        tur.fd(25)
        tur.left(180)
        tur.pd()
        tur.circle(20,360)
        tur.pu()
        tur.left(180)
        tur.fd(30)  
      
    elif letter == "P":
        tur.pu()
        tur.right(90)
        tur.fd(30)
        tur.right(90)
        tur.right(180)
        tur.pd()
        tur.left(90)
        tur.forward(60)
        tur.right(90)
        tur.forward(40)
        tur.right(90)
        tur.forward(40)
        tur.right(90)
        tur.forward(40)
        tur.pu()
        tur.right(90)
        tur.fd(40)
        tur.right(90)
        tur.fd(50)

            
    elif letter == "Q":
        tur.pu()
        tur.fd(5)
        tur.right(90)
        tur.fd(30)
        tur.pd()
        tur.left(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
        tur.right(45)
        tur.fd(10)
        tur.pu()
        tur.left(180)
        tur.fd(10)
        tur.right(45)
        tur.fd(30)
        tur.right(90)
        tur.fd(10) 
    elif letter == "R":
        tur.pu()
        tur.right(90)
        tur.fd(5)
        tur.pd()
        tur.fd(30)
        tur.pu()
        tur.right(180)
        tur.fd(30)
        tur.right(90)
        tur.pd()
        tur.fd(10)
        tur.right(90)
        tur.fd(10)
        tur.right(90)
        tur.fd(10)
        tur.left(90)
        tur.left(30)
        tur.fd(25)
        tur.pu()
        tur.left(150)
        tur.fd(35)
        tur.right(90)
        tur.fd(5)
    elif letter == "S":
        tur.pd()
        tur.fd(20)
        tur.left(180)
        tur.fd(20)
        tur.left(90)
        tur.fd(15)
        tur.left(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(15)
        tur.right(90)
        tur.fd(20)
        #fix
        tur.pu()
        tur.right(90)
        tur.fd(30)
        tur.right(90)
        tur.fd(30)
    elif letter == "T":
        tur.pu()
        tur.fd(5)
        tur.right(90)
        tur.fd(30)
        tur.pd()
        tur.left(90)
        tur.fd(30)
        tur.right(180)
        tur.fd(15)
        tur.left(90)
        tur.fd(30)
        tur.left(90)
        tur.pu()
        tur.fd(20)
        tur.left(90)
        tur.fd(30)
        tur.right(90)
        
    elif letter == "U":
        tur.pu()
        tur.fd(5)
        tur.right(90)
        tur.pd()
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(30)
        tur.pu()
        tur.fd(5)
        tur.right(90)
    elif letter == "V":
        tur.pu()
        tur.right(90)
        tur.fd(30)
        tur.left(90)
        tur.fd(20)
        tur.pd()
        tur.left(120)
        tur.forward(30)
        tur.left(180)
        tur.forward(30)
        tur.left(120)
        tur.forward(30)
        tur.right(60)
        tur.pu()
        tur.fd(30)
    elif letter == "W":
        tur.pu()
        tur.right(90)   
        tur.fd(30)
        tur.left(90)
        tur.pd()
        tur.left(120)
        tur.forward(30)
        tur.left(180)
        tur.forward(30)
        tur.left(120)
        tur.forward(20)
        tur.right(120)
        tur.forward(20)
        tur.left(120)
        tur.forward(30)
        tur.pu()
        tur.right(60)
        tur.fd(10)
    elif letter == "X":
        tur.pd()
        tur.right(45)
        tur.forward(30)
        tur.left(180)
        tur.forward(15)
        tur.right(90)
        tur.forward(15)
        tur.right(180)
        tur.forward(30)
        tur.pu()
        tur.right(180)
        tur.fd(30)
        tur.right(45)
    elif letter == "Y":
        tur.pu()
        tur.forward(15)
        tur.pd()
        tur.right(45)
        tur.forward(15)
        tur.left(90)
        tur.forward(15)
        tur.left(180)
        tur.forward(15)
        tur.left(45)
        tur.fd(20)
        tur.pu()
        tur.left(180)
        tur.fd(30)
        tur.right(90)
        tur.fd(20)
    elif letter == "Z":
        tur.pd()
        tur.forward(15)
        tur.right(135)
        tur.forward(25)
        tur.left(135)
        tur.forward(15)
        tur.left(180)
        tur.forward(15)
        tur.right(50)
        tur.pu()
    elif letter == "Ax":
        # code here
        tur.forward(40)
        
    else:
        #handles space, punctuation, and anything else
        tur.forward(40)
    
if __name__ == "__main__":
    window = turtle.Screen()
    tur = turtle.Turtle()
    tur.speed(0)
    tur.pu()
    tur.bk(500)
    tur.pd()
    #turtleLetter("box",tur)
    turtleLetter("A",tur)
    turtleLetter("B",tur)
    turtleLetter("C",tur)
    turtleLetter("D",tur)
    turtleLetter("E",tur)
    turtleLetter("F",tur)
    turtleLetter("G",tur)
    turtleLetter("H",tur)
    turtleLetter("I",tur)
    turtleLetter("J",tur)
    turtleLetter("K",tur)
    turtleLetter("L",tur)
    turtleLetter("M",tur)
    turtleLetter("N",tur)
    turtleLetter("O",tur)
    turtleLetter("P",tur)
    turtleLetter("Q",tur)
    turtleLetter("R",tur)
    turtleLetter("S",tur)
    turtleLetter("T",tur)
    turtleLetter("U",tur)
    turtleLetter("V",tur)
    turtleLetter("W",tur)
    turtleLetter("X",tur)
    turtleLetter("Y",tur)
    turtleLetter("Z",tur)
    

    window.exitonclick()
